apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-nginx
  labels: 
    app: twitter-nginx
spec:
  selector:
    matchLabels:
      app: twitter-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: twitter-nginx
    spec:
      containers:
      - name: twitter-nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: log
        emptyDir: {}